= SOLID and Design Patterns

Principios basicos de la POO (Programación Orientada a Objetos).

- S -> Single responsability principle.

- O -> Open / Closed principle.

- L -> Liskov substitution principle.

- I -> Interface segregation principle.

- D -> Dependency Inversion principle.

== Patterns
'''

En general los autores favorecen o se decantan por usar la composición en lugar de la herencia.

=== Creational

Facilitan la creación de objetos ocultando la lógica de creación y evitando el tener que usar el operador new directamente.
Proporciona más flexibilidad al programa a la hora de decidir que objetos necesitan ser creados para un determinado caso de uso.

- FACTORY: crea objetos ocultando al cliente la lógica necesaria para su instanciación. Es una versión simplificada del factory method pattern.

- FACTORY METHOD: define una interfaz para crear los objetos dejando a las subclases decidir qué clase debe ser instanciada. Se utiliza cuando tenemos lógica general que puede ser compartida en una clase y queremos que pueda cambiar el objeto que se utiliza en esta lógica.

- ABSTRACT FACTORY: factoría de factorías. Crea una instancia de varias familias de clases.

- SINGLETON: se asegura de que sólo existe una instancia de la clase y proporciona un único punto de acceso global a ella. El constructor debe ser privado.

- BUILDER: separar la construcción de un objeto complejo de su representación de tal forma que el mismo proceso de construcción sirva para crear distintas representaciones.

- PROTOTYPE: creamos una instancia nueva a partir de otra ya existente que sirve como prototipo. Se usa cuando la creación de una instancia totalmente nueva es muy costosa.

- CLONE: crea un nuevo objeto del mismo tipo y copia todos sus campos.

=== Structural

Se refieren a la composición de clases y objetos. Se usan para componer interfaces y definir formas de componer objetos para obtener nuevas funcionalidades.

- Adapter: la motivación es convertir la interfaz de una clase en otra interfaz que los clientes esperan. Permite que las clases funcionen juntas, lo que de otra forma no podría ser debido a interfaces incompatibles.

- Bridge: usado cuando tenemos que desacoplar una abstracción de su implementación para que las 2 partes puedan modificarse independientemente.

- Composite: permite que el cliente trate objetos individuales y compuestos de forma uniforme. Esta clase proporciona formas de modificar su grupo de objetos.

- Decorator: la motivacion es agregar nuevas funcionalidades a un objeto existente sin alterar su estructura. Crea una clase de decorador que envuelve la clase original y proporciona la uncionalidad adicional pero manteniendo la firma de los métodos de clase intactos.

- Facade: la motivacion es ocultar las complejidades del sistema y proporcionar una interfaz al cliente pero simplificada. Incluye una sola clase que proporciona métodos simplificados requeridos por el cliente y delega llamadas a métodos de clases de sistema existentes.
Esto no implica que no vayamos a poder acceder a los sistemas de más bajo nivel, simplemente es una interfaz de más alto nivel que nos simplificará ciertas operaciones.

- Flyweight: usado principalmente para reducir la cantidad de objetos creados y disminuir el uso de memoria (+ rendimiento). Proporciona formas de disminuir la cantidad de objetos, mejorando así la estructura de objetos de la aplicación.

- Proxy: la motivacion es controlar el acceso y lo hace proporcionando un substituto de otro objeto (real-object) y añadiendo restricciones.

- Virtual Proxy: la motivación en este caso es el performance. Retrasa la creación del objeto real al máximo. Se crea la instancia del objeto real la primera vez que el cliente realiza una solicitud al proxy.
Este recuerda la identidad de este objeto real y reenvía la solicitud a este objeto real. Luego, todas las solicitudes posteriores simplemente se reenvían directamente al objeto real encapsulado evitando la creación n veces.

=== Behavioral

Están específicamente relacionados con la comunicación entre objetos.

- Chain of Responsability: crea una cadena de objetos receptores para una solicitud. Este patrón desacopla al emisor y al receptor de una solicitud en función del tipo de solicitud.
En este patrón, normalmente cada receptor contiene una referencia a otro receptor. Si un objeto no puede manejar la solicitud, pasa el mismo al siguiente receptor y así sucesivamente.

- Command: una request se envuelve bajo un objeto como comando y se pasa al objeto invocador. El Invoker busca el objeto apropiado que puede manejar este comando y pasa el comando al objeto correspondiente que lo ejecuta.

- Interpreter: dado un idioma, defina una representación para su gramática junto con un intérprete que use la representación para interpretar oraciones en el lenguaje.

- Iterator: se utiliza para obtener una forma de acceder a los elementos de una colección de forma secuencial sin necesidad de conocer su representación subyacente.

- Visitor: el cliente representa con un objeto la operación que desea realizar sobre cada uno de los elementos de la estructura.
Permite definir una nueva operación sin cambiar o conocer la representacion subyacente de los elementos sobre los que opera.

- Mediator: se usa para reducir la complejidad de comunicación entre múltiples objetos o clases. Proporciona una clase de mediador que normalmente maneja todas las comunicaciones
entre diferentes clases y admite un fácil mantenimiento del código mediante un acoplamiento flexible.

- Memento: se usa para restaurar el estado de un objeto a un estado anterior. Capacidad de "punto de control".

- Observer: se usa cuando hay una relación one-to-many entre objetos, de tal forma que si un objeto cambia de estado, todos sus objetos dependientes serán notificados automáticamente para que realicen las actualizaciones oportunas.

- State: el comportamiento de clase cambia en función de su estado. Creamos objetos que representan varios estados y un objeto de contexto cuyo comportamiento varía a medida que cambia su objeto de estado.

- Strategy: definir una familia de algoritmos intercambiables. La estrategia permite al algoritmo varíar de forma independiente del cliente que lo usa.

- Template: define el esqueleto de un algoritmo en una operación, difiriendo algunos pasos a las subclases. El método de plantilla permite a las subclases redefinir ciertos pasos de un algoritmo pero sin cambiar la estructura global del algoritmo (marcado como final).