= SOLID and Design Patterns

Principios basicos de la POO (Programación Orientada a Objetos).

- S -> Single responsability principle.

- O -> Open / Closed principle.

- L -> Liskov substitution principle.

- I -> Interface segregation principle.

- D -> Dependency Inversion principle.

== Patterns
'''

=== Creational

Facilitan la creación de objetos ocultando la lógica de creación y evitando el tener que usar el operador new directamente.
Proporciona más flexibilidad al programa a la hora de decidir que objetos necesitan ser creados para un determinado caso de uso.

- Abstract Factory: factoría de factorías. Crea una instancia de varias familias de clases.

- Builder:  construcción de un objeto complejo paso a paso a partir de objetos sencillos.
Separa la construcción del objeto de su representación.

- Factory Method: lo utilizamos para crear objetos sin tener que especificar la clase exacta del objeto de que queremos crear y sin llamar a su constructor directamente.
Esto lo conseguimos creando los objetos con el factory method especificado en una interfaz e implementado en clases o en una clase base y sobreescrito en las clases que la extiendebn.

- Prototype: creamos una instancia nueva a partir de otra ya existente que sirve como prototipo. Se usa cuando la creación de una instancia totalmente nueva es muy costosa.

- Clone: crea un nuevo objeto del mismo tipo y copia todos sus campos.

- Singleton: se asegura de que solo existe una instancia de la clase y proporciona un unico punto de acceso global a ella. El constructor debe ser privado.

=== Structural

Se refieren a la composición de clases y objetos. El concepto de herencia se usa para componer interfaces y definir formas de componer objetos para obtener nuevas funcionalidades.

- Adapter: convierte la interfaz de una clase en otra interfaz que los clientes esperan. Permite que las clases funcionen juntas, lo que de otra forma no podría ser debido a interfaces incompatibles.
